project_name: golang-ci-test
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
nfpms:
 - maintainer: Maximilian Geberl
   description: golang CI test repo
   homepage: https://github.com/dergeberl/golang-ci-test
   formats:
     - deb
     - rpm
     - apk