project_name: golang-ci-test
archives:
  - builds:
    - golang-ci-test
    format: binary
    format_overrides:
      - goos: windows
        format: zip

builds:
  - id: "golang-ci-test"
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
nfpms:
 - maintainer: Maximilian Geberl
   description: golang CI test repo
   homepage: https://github.com/dergeberl/golang-ci-test
   formats:
     - deb
     - rpm
     - apk